package com.net2rent.net2rent_backend.model.enums;

public enum Permission {
    VIEW_ALL_INCIDENTS,
    SELF_ASSIGN_FROM_POOL,
    REGISTER_PHONE_INCIDENT,
    ASSIGN_OPERATOR,
    TRIAGE_INCIDENT,
    WORK_INCIDENT,
    RESOLVE_INCIDENT,
    MANAGE_CHECKLIST,
    WRITE_COMMENT,
    CLOSE_INCIDENT,
    REJECT_INCIDENT,
    VIEW_LODGINGS,
    MANAGE_LODGINGS,
    MANAGE_USERS
}