spring.application.name=net2rent-backend
spring.profiles.active=local

spring.datasource.url=jdbc:postgresql://localhost:5432/net2rent
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

app.jwt.secret=
app.jwt.expiration-ms=28800000