CREATE TABLE public.lodging_counter (
    id bigint NOT NULL,
    last_number integer NOT NULL
);

ALTER TABLE public.lodging_counter OWNER TO postgres;

ALTER TABLE public.lodging_counter ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lodging_counter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.lodging_counter
    ADD CONSTRAINT lodging_counter_pkey PRIMARY KEY (id);