--
-- PostgreSQL database dump
--

\restrict PiiOd0muYDCd7ZrCi5EeYYs8vmiOVuggD2nj8mseSqlCodnrM9CxPNGn3AvGWhr

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-08-26 15:54:37

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 18174)
-- Name: account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account (
    active boolean NOT NULL,
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.account OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 18173)
-- Name: account_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 18183)
-- Name: app_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_user (
    active boolean NOT NULL,
    account_id bigint NOT NULL,
    id bigint NOT NULL,
    last_login_at timestamp(6) without time zone,
    role character varying(20) NOT NULL,
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    CONSTRAINT app_user_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'COORDINATOR'::character varying, 'OPERATOR'::character varying])::text[])))
);


ALTER TABLE public.app_user OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 18182)
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 18202)
-- Name: incident; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.incident (
    minutes_spent integer,
    account_id bigint NOT NULL,
    assigned_at timestamp(6) without time zone,
    assignee_id bigint,
    closed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    lodging_id bigint NOT NULL,
    opened_at timestamp(6) without time zone NOT NULL,
    resolved_at timestamp(6) without time zone,
    started_at timestamp(6) without time zone,
    category character varying(20),
    priority character varying(20) NOT NULL,
    source character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    title character varying(150) NOT NULL,
    code character varying(255) NOT NULL,
    description text NOT NULL,
    guest_contact character varying(255),
    guest_first_name character varying(255) NOT NULL,
    guest_last_name character varying(255) NOT NULL,
    pause_reason text,
    reassignment_reason text,
    rejection_reason text,
    resolution_note text,
    CONSTRAINT incident_category_check CHECK (((category)::text = ANY ((ARRAY['PLUMBING'::character varying, 'ELECTRICITY'::character varying, 'HVAC'::character varying, 'APPLIANCES'::character varying, 'FURNITURE'::character varying, 'LOCKSMITH'::character varying, 'CLEANING'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT incident_priority_check CHECK (((priority)::text = ANY ((ARRAY['LOW'::character varying, 'NORMAL'::character varying, 'HIGH'::character varying, 'URGENT'::character varying])::text[]))),
    CONSTRAINT incident_source_check CHECK (((source)::text = ANY ((ARRAY['GUEST_PORTAL'::character varying, 'PHONE'::character varying])::text[]))),
    CONSTRAINT incident_status_check CHECK (((status)::text = ANY ((ARRAY['NEW'::character varying, 'ASSIGNED'::character varying, 'IN_PROGRESS'::character varying, 'PAUSED'::character varying, 'RESOLVED'::character varying, 'CLOSED'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.incident OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 18229)
-- Name: incident_checklist_item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.incident_checklist_item (
    done boolean NOT NULL,
    id bigint NOT NULL,
    incident_id bigint NOT NULL,
    text character varying(200) NOT NULL
);


ALTER TABLE public.incident_checklist_item OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 18228)
-- Name: incident_checklist_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.incident_checklist_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incident_checklist_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 18239)
-- Name: incident_comment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.incident_comment (
    author_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    incident_id bigint NOT NULL,
    text text NOT NULL
);


ALTER TABLE public.incident_comment OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 18238)
-- Name: incident_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.incident_comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incident_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 18252)
-- Name: incident_counter; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.incident_counter (
    last_number integer NOT NULL,
    year integer NOT NULL,
    account_id bigint NOT NULL,
    id bigint NOT NULL
);


ALTER TABLE public.incident_counter OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 18251)
-- Name: incident_counter_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.incident_counter ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incident_counter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 18262)
-- Name: incident_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.incident_history (
    actor_id bigint,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    incident_id bigint NOT NULL,
    event_type character varying(255) NOT NULL,
    new_value character varying(255),
    previous_value character varying(255)
);


ALTER TABLE public.incident_history OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 18261)
-- Name: incident_history_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.incident_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incident_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 18201)
-- Name: incident_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.incident ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incident_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 18274)
-- Name: lodging; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.lodging (
    active boolean NOT NULL,
    account_id bigint NOT NULL,
    id bigint NOT NULL,
    access_notes text,
    address character varying(255),
    name character varying(255) NOT NULL,
    pin_hash character varying(255) NOT NULL,
    ref character varying(255) NOT NULL
);


ALTER TABLE public.lodging OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 18273)
-- Name: lodging_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.lodging ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lodging_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4897 (class 2606 OID 18181)
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);


--
-- TOC entry 4899 (class 2606 OID 18200)
-- Name: app_user app_user_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_email_key UNIQUE (email);


--
-- TOC entry 4901 (class 2606 OID 18198)
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- TOC entry 4907 (class 2606 OID 18237)
-- Name: incident_checklist_item incident_checklist_item_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incident_checklist_item
    ADD CONSTRAINT incident_checklist_item_pkey PRIMARY KEY (id);


--
-- TOC entry 4903 (class 2606 OID 18227)
-- Name: incident incident_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incident
    ADD CONSTRAINT incident_code_key UNIQUE (code);


--
-- TOC entry 4909 (class 2606 OID 18250)
-- Name: incident_comment incident_comment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incident_comment
    ADD CONSTRAINT incident_comment_pkey PRIMARY KEY (id);


--
-- TOC entry 4911 (class 2606 OID 18260)
-- Name: incident_counter incident_counter_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incident_counter
    ADD CONSTRAINT incident_counter_pkey PRIMARY KEY (id);


--
-- TOC entry 4913 (class 2606 OID 18272)
-- Name: incident_history incident_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incident_history
    ADD CONSTRAINT incident_history_pkey PRIMARY KEY (id);


--
-- TOC entry 4905 (class 2606 OID 18225)
-- Name: incident incident_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incident
    ADD CONSTRAINT incident_pkey PRIMARY KEY (id);


--
-- TOC entry 4915 (class 2606 OID 18286)
-- Name: lodging lodging_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lodging
    ADD CONSTRAINT lodging_pkey PRIMARY KEY (id);


--
-- TOC entry 4917 (class 2606 OID 18288)
-- Name: lodging lodging_ref_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lodging
    ADD CONSTRAINT lodging_ref_key UNIQUE (ref);


--
-- TOC entry 4923 (class 2606 OID 18319)
-- Name: incident_comment fk2if6cp719obp3ckrtix2eoixq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incident_comment
    ADD CONSTRAINT fk2if6cp719obp3ckrtix2eoixq FOREIGN KEY (incident_id) REFERENCES public.incident(id);


--
-- TOC entry 4919 (class 2606 OID 18299)
-- Name: incident fk6pwrs1wuk0i5khvnux9dhr5dg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incident
    ADD CONSTRAINT fk6pwrs1wuk0i5khvnux9dhr5dg FOREIGN KEY (assignee_id) REFERENCES public.app_user(id);


--
-- TOC entry 4924 (class 2606 OID 18314)
-- Name: incident_comment fk8m1fqs8eh76mxsoqrtj0usb73; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incident_comment
    ADD CONSTRAINT fk8m1fqs8eh76mxsoqrtj0usb73 FOREIGN KEY (author_id) REFERENCES public.app_user(id);


--
-- TOC entry 4926 (class 2606 OID 18329)
-- Name: incident_history fk93sworiu2pjmaq9oykip0ci5a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incident_history
    ADD CONSTRAINT fk93sworiu2pjmaq9oykip0ci5a FOREIGN KEY (actor_id) REFERENCES public.app_user(id);


--
-- TOC entry 4925 (class 2606 OID 18324)
-- Name: incident_counter fk9btkoe2rh94wrsj1p4gs9ovlv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incident_counter
    ADD CONSTRAINT fk9btkoe2rh94wrsj1p4gs9ovlv FOREIGN KEY (account_id) REFERENCES public.account(id);


--
-- TOC entry 4927 (class 2606 OID 18334)
-- Name: incident_history fkbr9rqub0hitxolnf4g40pno17; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incident_history
    ADD CONSTRAINT fkbr9rqub0hitxolnf4g40pno17 FOREIGN KEY (incident_id) REFERENCES public.incident(id);


--
-- TOC entry 4922 (class 2606 OID 18309)
-- Name: incident_checklist_item fkgeklwt74009srsrwyi312wmrf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incident_checklist_item
    ADD CONSTRAINT fkgeklwt74009srsrwyi312wmrf FOREIGN KEY (incident_id) REFERENCES public.incident(id);


--
-- TOC entry 4928 (class 2606 OID 18339)
-- Name: lodging fkh1kv5aud7ynptsam08utcbibp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lodging
    ADD CONSTRAINT fkh1kv5aud7ynptsam08utcbibp FOREIGN KEY (account_id) REFERENCES public.account(id);


--
-- TOC entry 4920 (class 2606 OID 18304)
-- Name: incident fkiboxvyrv5oy85qlwdm2d797sc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incident
    ADD CONSTRAINT fkiboxvyrv5oy85qlwdm2d797sc FOREIGN KEY (lodging_id) REFERENCES public.lodging(id);


--
-- TOC entry 4921 (class 2606 OID 18294)
-- Name: incident fkn3klqgdjesy0aiwa8tnqij9nw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incident
    ADD CONSTRAINT fkn3klqgdjesy0aiwa8tnqij9nw FOREIGN KEY (account_id) REFERENCES public.account(id);


--
-- TOC entry 4918 (class 2606 OID 18289)
-- Name: app_user fkngs581vugannc8it964ohg2pt; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT fkngs581vugannc8it964ohg2pt FOREIGN KEY (account_id) REFERENCES public.account(id);


-- Completed on 2026-08-26 15:54:37

--
-- PostgreSQL database dump complete
--

\unrestrict PiiOd0muYDCd7ZrCi5EeYYs8vmiOVuggD2nj8mseSqlCodnrM9CxPNGn3AvGWhr

