--
-- PostgreSQL database dump
--

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account (
    active boolean NOT NULL,
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: account_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_user (
    active boolean NOT NULL,
    account_id bigint NOT NULL,
    id bigint NOT NULL,
    last_login_at timestamp(6) without time zone,
    role character varying(20) NOT NULL,
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    CONSTRAINT app_user_role_check CHECK (((role)::text = ANY (ARRAY[('ADMIN'::character varying)::text, ('COORDINATOR'::character varying)::text, ('OPERATOR'::character varying)::text])))
);


--
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: incident; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.incident (
    minutes_spent integer,
    account_id bigint NOT NULL,
    assigned_at timestamp(6) without time zone,
    assignee_id bigint,
    closed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    lodging_id bigint NOT NULL,
    opened_at timestamp(6) without time zone NOT NULL,
    resolved_at timestamp(6) without time zone,
    started_at timestamp(6) without time zone,
    category character varying(20),
    priority character varying(20) NOT NULL,
    source character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    title character varying(150) NOT NULL,
    code character varying(255) NOT NULL,
    description text NOT NULL,
    guest_contact character varying(255),
    guest_first_name character varying(255) NOT NULL,
    guest_last_name character varying(255) NOT NULL,
    pause_reason text,
    reassignment_reason text,
    rejection_reason text,
    resolution_note text,
    CONSTRAINT incident_category_check CHECK (((category)::text = ANY (ARRAY[('PLUMBING'::character varying)::text, ('ELECTRICITY'::character varying)::text, ('HVAC'::character varying)::text, ('APPLIANCES'::character varying)::text, ('FURNITURE'::character varying)::text, ('LOCKSMITH'::character varying)::text, ('CLEANING'::character varying)::text, ('OTHER'::character varying)::text]))),
    CONSTRAINT incident_priority_check CHECK (((priority)::text = ANY (ARRAY[('LOW'::character varying)::text, ('NORMAL'::character varying)::text, ('HIGH'::character varying)::text, ('URGENT'::character varying)::text]))),
    CONSTRAINT incident_source_check CHECK (((source)::text = ANY (ARRAY[('GUEST_PORTAL'::character varying)::text, ('PHONE'::character varying)::text]))),
    CONSTRAINT incident_status_check CHECK (((status)::text = ANY (ARRAY[('NEW'::character varying)::text, ('ASSIGNED'::character varying)::text, ('IN_PROGRESS'::character varying)::text, ('PAUSED'::character varying)::text, ('RESOLVED'::character varying)::text, ('CLOSED'::character varying)::text, ('REJECTED'::character varying)::text])))
);


--
-- Name: incident_checklist_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.incident_checklist_item (
    done boolean NOT NULL,
    id bigint NOT NULL,
    incident_id bigint NOT NULL,
    checked_by_id bigint,
    checked_at timestamp(6) without time zone,
    "position" integer DEFAULT 0 NOT NULL,
    text character varying(200) NOT NULL
);


--
-- Name: incident_checklist_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.incident_checklist_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incident_checklist_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: incident_comment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.incident_comment (
    author_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    incident_id bigint NOT NULL,
    text text NOT NULL
);


--
-- Name: incident_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.incident_comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incident_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: incident_counter; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.incident_counter (
    last_number integer NOT NULL,
    counter_year integer NOT NULL,
    account_id bigint NOT NULL,
    id bigint NOT NULL
);


--
-- Name: incident_counter_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.incident_counter ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incident_counter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: incident_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.incident_history (
    actor_id bigint,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    incident_id bigint NOT NULL,
    event_type character varying(255) NOT NULL,
    new_value character varying(255),
    previous_value character varying(255),
    note text
);


--
-- Name: incident_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.incident_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incident_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: incident_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.incident ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incident_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: incident_image; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.incident_image (
    id bigint NOT NULL,
    incident_id bigint NOT NULL,
    data bytea NOT NULL,
    content_type character varying(100) NOT NULL,
    uploaded_at timestamp(6) without time zone NOT NULL
);


--
-- Name: incident_image_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.incident_image ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incident_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lodging; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lodging (
    active boolean NOT NULL,
    account_id bigint NOT NULL,
    id bigint NOT NULL,
    access_notes text,
    address character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    pin_hash character varying(255) NOT NULL,
    ref character varying(255) NOT NULL
);


--
-- Name: lodging_counter; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lodging_counter (
    id bigint NOT NULL,
    last_number integer NOT NULL
);


--
-- Name: lodging_counter_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lodging_counter ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lodging_counter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lodging_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lodging ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lodging_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);


--
-- Name: app_user app_user_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_email_key UNIQUE (email);


--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- Name: incident_checklist_item incident_checklist_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.incident_checklist_item
    ADD CONSTRAINT incident_checklist_item_pkey PRIMARY KEY (id);


--
-- Name: incident_comment incident_comment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.incident_comment
    ADD CONSTRAINT incident_comment_pkey PRIMARY KEY (id);


--
-- Name: incident_counter incident_counter_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.incident_counter
    ADD CONSTRAINT incident_counter_pkey PRIMARY KEY (id);


--
-- Name: incident_history incident_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.incident_history
    ADD CONSTRAINT incident_history_pkey PRIMARY KEY (id);


--
-- Name: incident_image incident_image_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.incident_image
    ADD CONSTRAINT incident_image_pkey PRIMARY KEY (id);


--
-- Name: incident incident_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.incident
    ADD CONSTRAINT incident_pkey PRIMARY KEY (id);


--
-- Name: lodging_counter lodging_counter_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lodging_counter
    ADD CONSTRAINT lodging_counter_pkey PRIMARY KEY (id);


--
-- Name: lodging lodging_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lodging
    ADD CONSTRAINT lodging_pkey PRIMARY KEY (id);


--
-- Name: lodging lodging_ref_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lodging
    ADD CONSTRAINT lodging_ref_key UNIQUE (ref);


--
-- Name: incident uk_incident_account_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.incident
    ADD CONSTRAINT uk_incident_account_code UNIQUE (account_id, code);


--
-- Name: incident_counter uk_incident_counter_account_year; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.incident_counter
    ADD CONSTRAINT uk_incident_counter_account_year UNIQUE (account_id, counter_year);


--
-- Name: idx_checklist_item_checked_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_checklist_item_checked_by ON public.incident_checklist_item USING btree (checked_by_id);


--
-- Name: idx_checklist_item_incident; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_checklist_item_incident ON public.incident_checklist_item USING btree (incident_id);


--
-- Name: idx_comment_author; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_comment_author ON public.incident_comment USING btree (author_id);


--
-- Name: idx_comment_incident; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_comment_incident ON public.incident_comment USING btree (incident_id);


--
-- Name: idx_history_actor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_history_actor ON public.incident_history USING btree (actor_id);


--
-- Name: idx_history_incident; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_history_incident ON public.incident_history USING btree (incident_id);


--
-- Name: idx_image_incident; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_image_incident ON public.incident_image USING btree (incident_id);


--
-- Name: idx_incident_assignee; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_incident_assignee ON public.incident USING btree (assignee_id);


--
-- Name: idx_incident_lodging; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_incident_lodging ON public.incident USING btree (lodging_id);


--
-- Name: idx_lodging_account; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_lodging_account ON public.lodging USING btree (account_id);


--
-- Name: idx_user_account; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_account ON public.app_user USING btree (account_id);


--
-- Name: incident_checklist_item fk_checklist_item_checked_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.incident_checklist_item
    ADD CONSTRAINT fk_checklist_item_checked_by FOREIGN KEY (checked_by_id) REFERENCES public.app_user(id);


--
-- Name: incident_checklist_item fk_checklist_item_incident; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.incident_checklist_item
    ADD CONSTRAINT fk_checklist_item_incident FOREIGN KEY (incident_id) REFERENCES public.incident(id);


--
-- Name: incident_comment fk_comment_author; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.incident_comment
    ADD CONSTRAINT fk_comment_author FOREIGN KEY (author_id) REFERENCES public.app_user(id);


--
-- Name: incident_comment fk_comment_incident; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.incident_comment
    ADD CONSTRAINT fk_comment_incident FOREIGN KEY (incident_id) REFERENCES public.incident(id);


--
-- Name: incident_counter fk_counter_account; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.incident_counter
    ADD CONSTRAINT fk_counter_account FOREIGN KEY (account_id) REFERENCES public.account(id);


--
-- Name: incident_history fk_history_actor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.incident_history
    ADD CONSTRAINT fk_history_actor FOREIGN KEY (actor_id) REFERENCES public.app_user(id);


--
-- Name: incident_history fk_history_incident; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.incident_history
    ADD CONSTRAINT fk_history_incident FOREIGN KEY (incident_id) REFERENCES public.incident(id);


--
-- Name: incident fk_incident_account; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.incident
    ADD CONSTRAINT fk_incident_account FOREIGN KEY (account_id) REFERENCES public.account(id);


--
-- Name: incident fk_incident_assignee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.incident
    ADD CONSTRAINT fk_incident_assignee FOREIGN KEY (assignee_id) REFERENCES public.app_user(id);


--
-- Name: incident_image fk_incident_image_incident; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.incident_image
    ADD CONSTRAINT fk_incident_image_incident FOREIGN KEY (incident_id) REFERENCES public.incident(id);


--
-- Name: incident fk_incident_lodging; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.incident
    ADD CONSTRAINT fk_incident_lodging FOREIGN KEY (lodging_id) REFERENCES public.lodging(id);


--
-- Name: lodging fk_lodging_account; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lodging
    ADD CONSTRAINT fk_lodging_account FOREIGN KEY (account_id) REFERENCES public.account(id);


--
-- Name: app_user fk_user_account; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT fk_user_account FOREIGN KEY (account_id) REFERENCES public.account(id);


--
-- Name: incident_time_entry; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.incident_time_entry (
    id bigint NOT NULL,
    incident_id bigint NOT NULL,
    author_id bigint NOT NULL,
    concept character varying(100) NOT NULL,
    minutes integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL
);

ALTER TABLE public.incident_time_entry OWNER TO postgres;

ALTER TABLE public.incident_time_entry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incident_time_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.incident_time_entry
    ADD CONSTRAINT incident_time_entry_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.incident_time_entry
    ADD CONSTRAINT fk_time_entry_incident FOREIGN KEY (incident_id) REFERENCES public.incident(id);

ALTER TABLE ONLY public.incident_time_entry
    ADD CONSTRAINT fk_time_entry_author FOREIGN KEY (author_id) REFERENCES public.app_user(id);


CREATE INDEX idx_incident_account_opened
    ON public.incident USING btree (account_id, opened_at DESC);

--
-- PostgreSQL database dump complete
--
